# Generated by Django 4.1 on 2022-08-18 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_todo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='image',
            new_name='Image',
        ),
    ]
